baseURL = "https://www.juanvillela.me/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan Villela"

FootnoteReturnLinkContents = "â†©"
SectionPagesMenu = "main"

# Pygments Syntax Highlighting
pygmentsUseClassic = false
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=inline, lineseparator=<br>"
pygmentsStyle = "monokai"

[author]
  name = "Juan Villela"
  email = "hello@juanvillela.me"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  social = "fourjuaneight"

[params.meta]
  description = "A site about Juan Villela and a blog featuring his coding adventure"
  keywords = "coding, productivity, development, front-end"

[taxonomies]
  genre = "genre"
  categories = "categories"

[permalinks]
  archive = "/articles/:title/"
  genre = "/bookshelf/genre/:slug/"
  categories = "/articles/categories/:slug/"

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true

[outputs]
  home = ["html"]
  section = ["html", "jsonfeed"]

[params.google]
  analytics = "UA-119777735-2"