baseURL = "https://www.juanvillela.me/"
copyright = " 2018 Juan C Villela"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan C Villela"

FootnoteReturnLinkContents = "â†©"
SectionPagesMenu = "main"

# Pygments Syntax Highlighting
pygmentsUseClassic = false
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=inline, lineseparator=<br>"
pygmentsStyle = "monokai"

[author]
  name = "Juan C Villela"
  email = "hello@juanvillela.me"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  OpenLinksInNewWindow = true
  social = "fourjuaneight"

[params.google.analytics]
  trackerID = "UA-119777735-2"

[params.meta]
  description = "A site about Juan C Villela and a blog featuring his coding adventure"
  keywords = "coding, productivity, development, front-end"

[permalinks]
  blog = "/:title/"
  
[outputs]
  home = ["html", "rss"]