baseURL = "https://www.juanvillela.me/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan Villela"

FootnoteReturnLinkContents = "â†©"
SectionPagesMenu = "main"

# Pygments Syntax Highlighting
pygmentsUseClassic = false
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=inline, lineseparator=<br>"
pygmentsStyle = "monokai"

[author]
  name = "Juan Villela"
  email = "hello@juanvillela.me"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  OpenLinksInNewWindow = true
  social = "fourjuaneight"

[params.meta]
  description = "A site about Juan Villela and a blog featuring his coding adventure"
  keywords = "coding, productivity, development, front-end"

[permalinks]
  archive = "/:title/"
  
[outputs]
  home = ["html", "rss"]